[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "bike_model"
author = "patricia llull sperandio"
author-email = "patricia.llull@gmail.com"

